# Generated by Django 2.0.2 on 2018-02-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterName', models.CharField(max_length=30)),
                ('serverName', models.CharField(choices=[('bakal', 'bakal'), ('cain', 'cain'), ('casillas', 'casillas'), ('diregie', 'diregie'), ('hilder', 'hiler'), ('prey', 'prey'), ('siroco', 'siroco')], max_length=10)),
            ],
        ),
    ]
