# Generated by Django 2.0.2 on 2018-02-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switching', '0002_remove_user_servername'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serverName',
            field=models.CharField(choices=[('bakal', 'bakal'), ('cain', 'cain'), ('casillas', 'casillas'), ('diregie', 'diregie'), ('hilder', 'hiler'), ('prey', 'prey'), ('siroco', 'siroco')], default='cain', max_length=10),
        ),
    ]
